version: '3'
services:
        springapi:
                build:
                        context: backend/oho
                        dockerfile: Dockerfile
                image: springapi
                restart: always
                depends_on:
                        - maria
                        - red
                ports:
                        - "8080:8080"
                container_name: spring
        maria:
                image: mariadb:10.11.4
                container_name: maria
                environment:
                        MYSQL_ROOT_PASSWORD: ssafyohogame
                ports:
                        - "3306:3306"
                volumes:
                        - /home/ubuntu/db/data:/var/lib/mysql
                        - /home/ubuntu/db/initdb.d:/docker-entrypoint-initdb.d
                restart: always
        red:
                image: redis
                container_name: red
                command: ["--requirepass", "ssafyohogame"]
                ports:
                        - "6379:6379"


